version: '3'

services:
  clockmonster:
    image: hiett/clockmonster:latest
    ports: ['8080:8080']
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: clockmonster
      DB_PASSWORD: clockmonster

  postgres:
    image: postgres
    ports: ['5432:5432']
    environment:
      POSTGRES_USER: clockmonster
      POSTGRES_PASSWORD: clockmonster
      POSTGRES_DB: clockmonster