version: '3'

services:
  clockmonster1:
    image: quarkus/clockmonster-gradle-jvm
    depends_on: ['redis']
    environment:
      JOB_STORAGE_METHOD: REDIS
      REDIS_CONN_URL: 'redis://redis:6379'

  clockmonster2:
    image: quarkus/clockmonster-gradle-jvm
    depends_on: ['redis']
    environment:
      JOB_STORAGE_METHOD: REDIS
      REDIS_CONN_URL: 'redis://redis:6379'

  clockmonster3:
    image: quarkus/clockmonster-gradle-jvm
    depends_on: ['redis']
    environment:
      JOB_STORAGE_METHOD: REDIS
      REDIS_CONN_URL: 'redis://redis:6379'

  clockmonster4:
    image: quarkus/clockmonster-gradle-jvm
    depends_on: ['redis']
    environment:
      JOB_STORAGE_METHOD: REDIS
      REDIS_CONN_URL: 'redis://redis:6379'

  redis:
    image: redis
    ports: ['6379:6379']